In [3]:
import cv2
import numpy as np
import pandas as pd
import os
from os.path import join
import re
a = "S902A050.clean.npy"
regex_sample_action = "(A\d{3}).clean.npy"
matched = re.findall(regex_sample_action,a)

print (matched)



['A050']


In [39]:
A = np.array([[0,0],[0,4]])

res = np.arctan2([4,3],[0,3])
print(res)
np.pi/4

[1.57079633 0.78539816]


0.7853981633974483

In [59]:
A = np.array([1,2,0,3,0,0,5])
B = []
B.append(A)
print (B)

[array([1, 2, 0, 3, 0, 0, 5])]


In [9]:
import matplotlib.pyplot as plt

a = [1,2,3]
b= [2,3,4]
c = [3,4,5]

s = list(zip(a,b,c))
s

[(1, 2, 3), (2, 3, 4), (3, 4, 5)]

In [23]:
a = [1,2,3,4]
b = [3,4,5,6]
c = set(a).union(set(b))
c

{1, 2, 3, 4, 5, 6}

In [29]:
a = [1,2,3,4]
a = np.append(a, ['5x4','abd'])
a

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
i = 1.234
print (isinstance(i, (int,float)))

In [8]:
import numpy as np

a = np.zeros((1,2,3,4))
print(a.size)
print(a)

24
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [2]:
import cv2

img = cv2.imread("media/z-neg-car.jpg")

cv2.imwrite("media/1.png",img)

KeyboardInterrupt: 

In [3]:
mypath = "D:\\poland\\PyCharm\\Semester III\\EAISR\\human-pose-proj\\yoga-pose-dataset\\train\\warrior2\\RoI-HOG"

import cv2
from os import listdir
from os.path import isfile, join

onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

for img in onlyfiles:
    img_path = join(mypath, img)
    img_data = cv2.imread(img_path)
    img_data = cv2.resize(img_data,(256,256))
    cv2.imwrite(img_path,img_data)

In [5]:
from os.path import join

dir = "a/b/c"
name1 = "d"
name2 = "e"

path = join(dir,name1,name2)
print(path)

a/b/c\d\e
